name: Post welcome comment
on:
  pull_request:
    types: [opened]
  push:
    branches: [ main ]
jobs:
  build:
    environment: [test, dev]
    runs-on: ubuntu-latest
    steps:
    - name: "Try env"
      run: echo ${{ env.VALUE }}

